# Generated by Django 3.0.6 on 2020-12-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='sold',
        ),
    ]
