# Generated by Django 3.0.6 on 2020-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20201220_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='profit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
