# Generated by Django 3.0.6 on 2021-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210304_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
